configuration: Debug

# restore NuGet packages before running MSBuild
before_build:
- nuget restore
 
# package Web Application project for Web Deploy
build:
verbosity: detailed
project: VSTestAllureTestLogger.sln
